version: "3.8"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=mongo
      - DB_PORT=27017
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
